comment_edit:
  path: /comment/{id}/edit
  controller: CommentBundle:Comment:edit

comment_delete:
  path: /comment/{id}/delete
  controller: CommentBundle:Comment:remove

comment_reply:
  path: /comment/{id}/reply
  controller: CommentBundle:Comment:reply
